content:
  - name: modes
    label: "🤖 Bob Modes"
    type: collection
    path: _modes
    fields:
      - name: title
        label: "Mode Name"
        type: string
        required: true
      - name: type
        label: "Type"
        type: select
        required: true
        options:
         values: ["Premium", "Custom"]
         multiple: false
         placeholder: "Use-case Type"
      - name: industry
        label: "Industry"
        type: select
        required: true
        options:
          values: ["Cross","AI", "Marketing", "Sales", "Customer Service", "Finance", "HR", "Operations", "Other"]
          placeholder: "Select Industry"
          multiple: true
      - name: body
        label: "Mode Description"
        type: rich-text
        required: true
      - name: link
        label: "Mode Github Link"
        type: string
        required: true
      - name : demo
        label: "Mode Demo Link"
        type: string
        required: false
      - name: lab
        label: "Mode Lab Link"
        type: string
        required: false
  - name: labs
    label: "🤖 Bob Labs"
    type: collection
    path: _labs
    fields:
      - name: title
        label: "Lab Title"
        type: string
        required: true
      - name: domain
        label: "Domain"
        type: select
        required: true
        options:
         values: ["Data", "Automation", "Security"]
         multiple: false
         placeholder: "Select Domain"
      - name: duration
        label: "Estimated Time (e.g., 45 mins)"
        type: string
        required: true
      - name: body
        label: "Lab Description"
        type: rich-text
        required: true
      - name: link
        label: "Lab Link"
        type: string
        required: true
  - name: demos
    label: "💻 Bob Demos"
    type: collection
    path: _demos
    fields:
      - name: title
        label: "Demo Name"
        type: string
        required: true
      - name: domain
        label: "Domain"
        type: select
        required: true
        options:
         values: ["Data", "Automation", "Security"]
         multiple: false
         placeholder: "Select Domain"
      - name: body
        label: "Demo Description"
        type: rich-text
        required: true
      - name: link
        label: "Demo Link"
        type: string
        required: true
  - name: use-cases
    label: "📋 Bob Usecases"
    type: collection
    path: _use-cases
    fields:
      - name: title
        label: "Use-case Title"
        type: string
        required: true
      - name: type
        label: "Type"
        type: select
        required: true
        options:
         values: ["Technical", "Business"]
         multiple: false
         placeholder: "Use-case Type"
      - name: domain
        label: "Domain"
        type: select
        required: true
        options:
         values: ["Data", "Automation", "Security"]
         multiple: false
         placeholder: "Select Domain"
      - name: body
        label: "Use-case Description"
        type: rich-text
        required: true
      - name: link
        label: "Use-case Link"
        type: string
        required: true
      - name: demo
        label: "Demo Link"
        type: string
        required: false
      - name: mode
        label: "Mode Link"
        type: string
        required: false
  - name: learning-content
    label: "Bob Learning Content"
    type: collection
    path: _learning
    fields:
      - name: title
        label: "Document Title"
        type: string
        required: true
      - name: body
        label: "Document Description"
        type: rich-text
        required: true
      - name: link
        label: "Document Link"
        type: string
        required: true
  - name: bob101
    label: "Bob 101"
    type: collection
    path: _bob101
    fields:
      - name: title
        label: "Document Title"
        type: string
        required: true
      - name: body
        label: "Document Description"
        type: rich-text
        required: true
      - name: link
        label: "Document Link"
        type: string
        required: true
  - name: skills
    label: "🤖 Bob Skills"
    type: collection
    path: _skills
    fields:
      - name: title
        label: "Skill Name"
        type: string
        required: true
      - name: industry
        label: "Industry"
        type: select
        required: true
        options:
          values: ["Cross","AI", "Marketing", "Sales", "Customer Service", "Finance", "HR", "Operations", "Other"]
          placeholder: "Select Industry"
          multiple: true
      - name: body
        label: "Skill Description"
        type: rich-text
        required: true
      - name: link
        label: "Skill Github Link"
        type: string
        required: true

# Made with Bob
